### ISSUE TITLE
Upload Extension for VSCodium

### ISSUE THREAD

**Issue by gsicilia82** [nokxs/iobroker-javascript-vs-code-extension#80]
As I could read, VSCodium is the real open source counterpart from VSCode. Is it possible to upload this extension to open source marketplace https://open-vsx.org/ ? Or does it leads to a big effort regarding your source code?
For sure, this is a feature request not a bug 😉
I would like to switch to VSCodium. But I don't want to loose this extension.

**Comment by nokxs** [comment]
I havn't tested the extension with VSCodium, but I made it available Open-VSX: [iobroker.javascript](https://open-vsx.org/extension/nokxs/iobroker-javascript). 

I updated the build process, in order to publish the extension always in the VS Code marketplace and Open VSX. 

Could you give me some feedback, if the extension works correctly with VSCodium?

**Comment by gsicilia82** [comment]
Cool, I will test it today

**Comment by gsicilia82** [comment]
It works without any issues. Thanks for your effort.

**Comment by nokxs** [comment]
Perfect, thanks for testing 👍. I will close the issue now.
